### ISSUE TITLE
Add proper contributor attribution for Vocabulary section in TOC

### ISSUE THREAD

**Issue by geealbers** [thegetty/bronze-guidelines#129]
TOC should list "Edited by Jane Bassett and David Bourgarit" for the Vocabulary section. Currently, we're just suppressing the natural output (that lists all the contributors to the page) until this can be figured out

```css
/* TEMPORARY until we figure out how to display the editors */
#contents.quire-page .toc-list a[href='/vocabulary/'] .contributor-divider,
#contents.quire-page .toc-list a[href='/vocabulary/'] .contributor {
  display: none;
}
```
