### ISSUE TITLE
Add new paragraph of text and three figure images on x-ray 360s

### ISSUE THREAD

**Issue by geealbers** [thegetty/bronze-guidelines#142]
A new paragraph of text and three new figures (one static, two 360s) are being added to II.3.

@ruthlane I assume the figure numbering should just add to the end of our current figures, so would be figs. 563, 564, and 565. However, when I was looking at the video posters for (issue #141) I noted two figures that are essentially duplicates. They are figs 44 and 498. Info below. What do you think of taking the opportunity to replace fig 498 with one of the new x-ray ones?

<img width="1322" alt="Screen Shot 2023-03-06 at 2 38 51 PM" src="https://user-images.githubusercontent.com/7796401/223267462-1d05138e-00fc-485a-9bb2-719191f44e51.png">

```yaml
label: "Figure 44"
caption: "Sprue system on a reproduction casting. Ubaldo Vitali (American, b. 1944), Reproduction of a Lion Aquamanile, 
Maplewood, New Jersey, 2006, H. 19 cm, after Aquamanile in the Form of a Lion, probably northern Germany, 12th century, 
H. 19.5 cm (Metropolitan Museum of Art, gift of Irwin Untermyer, 1964, inv. 64.101.149). See [video 8](/visual-atlas/#vid-08){target=_blank}."
```

```yaml
label: "Figure 498"
caption: "Cast reproduction of an aquamanile after removal of its investment, still retaining the evidence of its sprueing. 
Ubaldo Vitali (American, b. 1944), Reproduction of a Lion Aquamanile, Maplewood, New Jersey, 2006, H. 19 cm, after 
Aquamanile in the Form of a Lion, probably northern Germany, 12th century, H. 19.5 cm (Metropolitan Museum of Art, gift of 
Irwin Untermyer, 1964, inv. 64.101.1491). See %%Barnet and Dandridge 2006%%."
```

*Noting here that the accession number in the second caption has an extra "1" at the end, but the rest of the tombstone detail is the same.*
